// Config plugin: give built Android APKs a descriptive, versioned filename
// (uctenkomat-v<version>-<buildType>.apk) instead of the default app-release.apk.
// The native android/ dir is gitignored and regenerated by `expo prebuild`, so this
// lives as a plugin to survive regeneration.
const { withAppBuildGradle } = require("@expo/config-plugins");

const RENAME_BLOCK = `    // Added by withApkName config plugin.
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "uctenkomat-v\${variant.versionName}-\${variant.buildType.name}.apk"
        }
    }
`;

module.exports = function withApkName(config) {
  return withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;
    if (contents.includes("withApkName config plugin")) return cfg; // idempotent
    // Insert just before the android block's `buildTypes {`.
    contents = contents.replace(/(\n {4}buildTypes \{)/, `\n${RENAME_BLOCK}$1`);
    cfg.modResults.contents = contents;
    return cfg;
  });
};
